### PR TITLE
Fixed the Typos

### PR DESCRIPTION
**Pull request by nelsonuprety1**
Hello, i was going through the docs and found more typos on the createForm page. So,i opened this PR to fix those changes. 

I believe these changes will greatly enhance the readability and professionalism of the project. Please let me know if there's anything else I can do to improve the content.

Regards, 
Nelson

### CODE REVIEW

**Comment by nelsonuprety1** [comment]
@jucian0  while going through the docs i found more typos and grammatical structure which needed to be fixed so i opened this PR. Thank you

**Comment by jucian0** [comment]
Thanks again!!!

**Comment by nelsonuprety1** [comment]
Im glad i could help 😃

**Comment by jucian0** [comment]
@all-contributors please add @nelsonuprety1  for <contributions>

**Comment by jucian0** [comment]
https://github.com/all-contributors please add @nelsonuprety1 for code

**Comment by nelsonuprety1** [comment]
Thank you

**Pull request merged**
